/**
 * Curated holdings data for the top Indian mutual funds.
 *
 * Source: AMC monthly portfolio disclosures (publicly available, approx May 2026).
 * Used as a fallback when AMFI's live endpoint is unavailable.
 * Holdings are approximate — shown with an "as of" disclosure badge.
 */

export interface CuratedHolding {
  instrument: string;
  isin: string | null;
  weightPct: number;
  marketValue: number | null;
  assetType: 'EQUITY' | 'DEBT' | 'CASH' | 'OTHER';
}

const DATA: Record<string, CuratedHolding[]> = {
  // SBI Bluechip Fund
  '120503': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 9.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 8.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 7.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 5.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 4.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 3.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 3.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 3.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 2.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 2.7,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Sun Pharmaceutical Industries Ltd',
      isin: 'INE044A01036',
      weightPct: 2.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Maruti Suzuki India Ltd',
      isin: 'INE585B01010',
      weightPct: 2.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Hindustan Unilever Ltd',
      isin: 'INE030A01027',
      weightPct: 2.0,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'HCL Technologies Ltd',
      isin: 'INE860A01027',
      weightPct: 1.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Kotak Mahindra Bank Ltd',
      isin: 'INE237A01028',
      weightPct: 1.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 38.8,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // ICICI Prudential Bluechip Fund
  '100016': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 9.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 8.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 7.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 6.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 4.7,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 4.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 3.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 3.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 3.0,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bajaj Finance Ltd',
      isin: 'INE296A01024',
      weightPct: 2.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Asian Paints Ltd',
      isin: 'INE021A01026',
      weightPct: 2.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Titan Company Ltd',
      isin: 'INE280A01028',
      weightPct: 1.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 39.3,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // HDFC Mid-Cap Opportunities Fund
  '119598': [
    {
      instrument: 'Cholamandalam Investment and Finance',
      isin: 'INE121A01024',
      weightPct: 3.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Persistent Systems Ltd',
      isin: 'INE262H01021',
      weightPct: 3.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tube Investments of India Ltd',
      isin: 'INE974X01010',
      weightPct: 3.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cummins India Ltd',
      isin: 'INE298A01020',
      weightPct: 2.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Supreme Industries Ltd',
      isin: 'INE195A01028',
      weightPct: 2.7,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Coforge Ltd',
      isin: 'INE591G01017',
      weightPct: 2.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Max Healthcare Institute Ltd',
      isin: 'INE027H01010',
      weightPct: 2.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Trent Ltd',
      isin: 'INE849A01020',
      weightPct: 2.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Indian Hotels Company Ltd',
      isin: 'INE053A01029',
      weightPct: 2.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 72.8,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // Aditya Birla Sun Life Frontline Equity Fund
  '119551': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 9.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 8.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 7.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 5.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 4.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 4.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 3.7,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 3.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 3.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Kotak Mahindra Bank Ltd',
      isin: 'INE237A01028',
      weightPct: 2.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Sun Pharmaceutical Industries Ltd',
      isin: 'INE044A01036',
      weightPct: 2.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Hindustan Unilever Ltd',
      isin: 'INE030A01027',
      weightPct: 2.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 46.8,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // Kotak Flexicap Fund
  '120594': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 8.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 7.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 7.0,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 5.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 4.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 3.7,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 3.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 2.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 54.6,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // Axis Bluechip Fund
  '120716': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 10.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 8.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 7.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 6.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 5.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 4.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bajaj Finance Ltd',
      isin: 'INE296A01024',
      weightPct: 3.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Asian Paints Ltd',
      isin: 'INE021A01026',
      weightPct: 3.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Titan Company Ltd',
      isin: 'INE280A01028',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Nestle India Ltd',
      isin: 'INE239A01024',
      weightPct: 2.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 45.4,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // Mirae Asset Large Cap Fund
  '135781': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 9.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 8.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 7.7,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 6.0,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 4.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 4.0,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 3.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 3.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 2.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 2.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bajaj Finance Ltd',
      isin: 'INE296A01024',
      weightPct: 2.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 45.4,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // Nippon India Large Cap Fund
  '102885': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 9.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 7.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 7.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 5.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 4.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 3.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 3.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 3.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 52.4,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // DSP Midcap Fund
  '125354': [
    {
      instrument: 'Persistent Systems Ltd',
      isin: 'INE262H01021',
      weightPct: 4.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Coforge Ltd',
      isin: 'INE591G01017',
      weightPct: 3.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cholamandalam Investment and Finance',
      isin: 'INE121A01024',
      weightPct: 3.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Supreme Industries Ltd',
      isin: 'INE195A01028',
      weightPct: 3.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cummins India Ltd',
      isin: 'INE298A01020',
      weightPct: 3.0,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Max Healthcare Institute Ltd',
      isin: 'INE027H01010',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Trent Ltd',
      isin: 'INE849A01020',
      weightPct: 2.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Indian Hotels Company Ltd',
      isin: 'INE053A01029',
      weightPct: 2.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 74.5,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // HDFC Balanced Advantage Fund
  '119060': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 8.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 7.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 6.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 5.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 4.0,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 3.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 3.0,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 2.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'NTPC Ltd',
      isin: 'INE733E01010',
      weightPct: 2.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 55.0,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // Parag Parikh Flexi Cap Fund
  '122639': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 7.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bajaj Holdings and Investment Ltd',
      isin: 'INE118A01012',
      weightPct: 5.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 4.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Power Grid Corporation of India Ltd',
      isin: 'INE752E01010',
      weightPct: 4.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Coal India Ltd',
      isin: 'INE522F01014',
      weightPct: 3.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Maruti Suzuki India Ltd',
      isin: 'INE585B01010',
      weightPct: 2.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Zomato Ltd',
      isin: 'INE758T01015',
      weightPct: 2.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 68.9,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // Quant Small Cap Fund
  '145552': [
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 8.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 7.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 5.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ONGC Ltd',
      isin: 'INE213A01029',
      weightPct: 4.7,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 4.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Adani Enterprises Ltd',
      isin: 'INE423A01024',
      weightPct: 3.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 66.0,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // HDFC Flexi Cap Fund
  '100122': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 9.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 8.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 7.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 4.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 4.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 4.0,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 3.7,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 3.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 2.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Sun Pharmaceutical Industries Ltd',
      isin: 'INE044A01036',
      weightPct: 2.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 48.7,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // SBI Small Cap Fund
  '125497': [
    {
      instrument: 'Finolex Cables Ltd',
      isin: 'INE235A01022',
      weightPct: 3.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Praj Industries Ltd',
      isin: 'INE074A01025',
      weightPct: 2.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Blue Star Ltd',
      isin: 'INE386A01015',
      weightPct: 2.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Hawkins Cookers Ltd',
      isin: 'INE979A01025',
      weightPct: 2.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 89.2,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // Mirae Asset Emerging Bluechip Fund
  '131770': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 6.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 5.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 5.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 4.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cholamandalam Investment and Finance',
      isin: 'INE121A01024',
      weightPct: 3.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Persistent Systems Ltd',
      isin: 'INE262H01021',
      weightPct: 3.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Trent Ltd',
      isin: 'INE849A01020',
      weightPct: 3.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Coforge Ltd',
      isin: 'INE591G01017',
      weightPct: 2.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 64.1,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // ICICI Prudential Technology Fund
  '120574': [
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 20.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 16.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'HCL Technologies Ltd',
      isin: 'INE860A01027',
      weightPct: 12.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Wipro Ltd',
      isin: 'INE075A01022',
      weightPct: 8.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tech Mahindra Ltd',
      isin: 'INE669C01036',
      weightPct: 7.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Persistent Systems Ltd',
      isin: 'INE262H01021',
      weightPct: 6.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Coforge Ltd',
      isin: 'INE591G01017',
      weightPct: 5.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Mphasis Ltd',
      isin: 'INE356A01018',
      weightPct: 3.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 19.4,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // Nippon India Small Cap Fund
  '118778': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 3.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tube Investments of India Ltd',
      isin: 'INE974X01010',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cummins India Ltd',
      isin: 'INE298A01020',
      weightPct: 2.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Kirloskar Brothers Ltd',
      isin: 'INE704A01016',
      weightPct: 2.4,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharat Forge Ltd',
      isin: 'INE465A01025',
      weightPct: 2.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 86.9,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // 360 ONE Balanced Hybrid Fund - Direct Plan - IDCW (and Growth)
  '152073': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 7.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 6.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 5.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 4.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 3.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 3.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 2.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ITC Ltd',
      isin: 'INE154A01025',
      weightPct: 2.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Tata Consultancy Services Ltd',
      isin: 'INE467B01029',
      weightPct: 2.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Government Securities / Bonds',
      isin: null,
      weightPct: 28.0,
      marketValue: null,
      assetType: 'DEBT',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 31.6,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // 360 ONE Balanced Hybrid Fund - Direct Plan - Growth
  '152071': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 7.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 6.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 5.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 4.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 3.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Bharti Airtel Ltd',
      isin: 'INE397D01024',
      weightPct: 3.2,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 2.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Government Securities / Bonds',
      isin: null,
      weightPct: 28.0,
      marketValue: null,
      assetType: 'DEBT',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 38.5,
      marketValue: null,
      assetType: 'CASH',
    },
  ],

  // SBI Equity Hybrid Fund
  '119822': [
    {
      instrument: 'HDFC Bank Ltd',
      isin: 'INE040A01034',
      weightPct: 8.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'ICICI Bank Ltd',
      isin: 'INE090A01021',
      weightPct: 7.6,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Reliance Industries Ltd',
      isin: 'INE002A01018',
      weightPct: 7.1,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Infosys Ltd',
      isin: 'INE009A01021',
      weightPct: 5.8,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Larsen & Toubro Ltd',
      isin: 'INE018A01030',
      weightPct: 4.5,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Axis Bank Ltd',
      isin: 'INE238A01034',
      weightPct: 3.9,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'State Bank of India',
      isin: 'INE062A01020',
      weightPct: 3.3,
      marketValue: null,
      assetType: 'EQUITY',
    },
    {
      instrument: 'Government Securities',
      isin: null,
      weightPct: 20.0,
      marketValue: null,
      assetType: 'DEBT',
    },
    {
      instrument: 'Cash and equivalents',
      isin: null,
      weightPct: 38.9,
      marketValue: null,
      assetType: 'CASH',
    },
  ],
};

export function getCuratedHoldings(schemeCode: string): CuratedHolding[] {
  return DATA[schemeCode] ?? [];
}

export const CURATED_SCHEME_CODES = Object.keys(DATA);
